/*	By Jiashan Wu
	11 September 2015
*/


public class Song {
	public static void main(String args[]){
		System.out.println(
			"\nYou are now about to witness the strength of street knowledge\n"
		+	"\n[Verse One: Ice Cube]\n"
		+	"\nStraight outta Compton, crazy motherfucker named Ice Cube\n"
		+ 	"From the gang called Niggaz With Attitudes\n"
		+ 	"When I\'m called off, I got a sawed off\n"
		+ 	"Squeeze the trigger, and bodies are hauled off\n"
		+ 	"You too, boy, if ya fuck with me\n"
		+ 	"The police are gonna hafta come and get me\n"
		+ 	"Off yo ass, that's how I'm goin out\n"
		+ 	"For the punk motherfuckers that\'s showin out\n"
		+ 	"Niggaz start to mumble, they wanna rumble\n"
		+ 	"Mix em and cook em in a pot like gumbo\n"
		+ 	"Goin off on a motherfucker like that\n"
		+ 	"with a gat that\'s pointed at yo ass\n"
		+ 	"So give it up smooth\n"
		+ 	"Ain\'t no tellin when I\'m down for a jack move\n"
		+ 	"Here\'s a murder rap to keep yo dancin\n"
		+ 	"with a crime record like Charles Manson\n"
		+ 	"AK-47 is the tool\n"
		+ 	"Don\'t make me act the motherfuckin fool\n"
		+ 	"Me you can go toe to toe, no maybe\n"
		+ 	"I\'m knockin niggaz out tha box, daily\n"
		+ 	"yo weekly, monthly and yearly\n"
		+ 	"until them dumb motherfuckers see clearly\n"
		+ 	"that I\'m down with the capital C-P-T\n"
		+ 	"Boy you can\'t fuck with me\n"
		+ 	"So when I\'m in your neighborhood, you better duck\n"
		+ 	"Coz Ice Cube is crazy as fuck\n"
		+ 	"As I leave, believe I\'m stompin\n"
		+ 	"but when I come back, boy, I\'m comin straight outta Compton\n"
		+	"\n[Chorus:]\n"
		+	"\n(City of Compton, City of Compton)\n"
		+ 	"\n[Eazy E] Yo Ren\n"
		+	"[MC Ren] Whassup?\n"
		+	"[Eazy E] Tell em where you from!\n"
		+	"\n[Verse Two: MC Ren]\n"
		+	"\nStraight outta Compton, another crazy ass nigga\n"
		+	"More punks I smoke, yo, my rep gets bigger\n"
		+	"I\'m a bad motherfucker and you know this\n"
		+	"But the pussy ass niggaz don\'t show this\n"
		+	"But I don\'t give a fuck, I\'ma make my snaps\n"
		+	"If not from the records, from jackin the crops\n"
		+	"Just like burglary, the definition is \'jackin\'\n"
		+	"And when illegally armed it\'s called \'packin\'\n"
		+	"Shoot a motherfucker in a minute\n"
		+	"I find a good piece o\' pussy, I go up in it\n"
		+	"So if you\'re at a show in the front row\n"
		+	"I\'m a call you a bitch or dirty-ass ho\n"
		+	"You\'ll probably get mad like a bitch is supposed to\n"
		+	"But that shows me, slut, you\'re composed to\n"
		+	"a crazy muthafucker from tha street\n"
		+	"Attitude legit cause I\'m tearin up shit\n"
		+	"MC Ren controls the automatic\n"
		+	"For any dumb muthafucker that starts static\n"
		+	"Not the right hand cause I\'m the hand itself\n" 
		+	"every time I pull a AK off the shelf\n" 
		+	"The security is maximum and that\'s a law\n"
		+	"R-E-N spells Ren but I\'m raw\n"
		+	"See, coz I\'m the motherfuckin villain\n"
		+	"The definition is clear, you\'re the witness of a killin\n"
		+	"that\'s takin place without a clue\n"
		+	"And once you\'re on the scope, your ass is through\n"
		+	"Look, you might take it as a trip\n"
		+	"but a nigga like Ren is on a gangsta tip\n"
		+	"Straight outta Compton...\n"
		+	"\n[Chorus:]\n"
		+	"\n(City of Compton, City of Compton)\n"
		+	"\n[Dr. Dre] Eazy is his name and the boy is comin...\n"
		+	"\n[Verse Three: Eazy-E]\n"
		+	"\n...straight outta Compton\n"
		+	"is a brotha that\'ll smother yo\' mother\n"
		+	"and make ya sister think I love her\n"
		+	"Dangerous motherfucker raises hell\n"
		+	"And if I ever get caught I make bail\n"
		+	"See, I don\'t give a fuck, that\'s the problem\n"
		+	"I see a motherfuckin cop I don\'t dodge him\n"
		+	"But I\'m smart, lay low, creep a while\n"
		+	"And when I see a punk pass, I smile\n"
		+	"To me it\'s kinda funny, the attitude showin a nigga drivin\n"
		+	"but don't know where the fuck he\'s going, just rollin\n"
		+	"lookin for the one they call Eazy\n"
		+	"But here\'s a flash, they never seize me\n"
		+	"Ruthless! Never seen like a shadow in the dark\n"
		+	"except when I unload, see I\'ll get over the hesitation\n"
		+	"and hear the scream of the one who got the last penetration\n"
		+	"Give a little gust of wind and I\'m jettin\n"
		+	"But leave a memory no one\'ll be forgettin\n"
		+	"So what about the bitch who got shot? Fuck her!\n"
		+	"You think I give a damn about a bitch? I ain\'t a sucker!\n"
		+	"This is the autobiography of the E, and if you ever fuck with me\n"
		+	"You\'ll get taken by a stupid dope brotha who will smother\n"
		+	"word to the motherfucker, straight outta Compton\n"
		+	"\n[Chorus:]\n"
		+	"\n(City of Compton, City of Compton)\n"
		+	"\n(Damn that shit was dope!)\n"
		);
	}
}